# Generated by Django 4.2.26 on 2026-04-07 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_alter_review_options_alter_review_avatar_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('short_description', models.CharField(max_length=240)),
                ('story', models.TextField()),
                ('ingredients', models.TextField(help_text='One ingredient per line')),
                ('steps', models.TextField(help_text='One step per line')),
                ('servings', models.PositiveIntegerField(default=2)),
                ('prep_time_minutes', models.PositiveIntegerField(default=30)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('allow_custom_orders', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_recipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recipe Share',
                'verbose_name_plural': 'Recipe Shares',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RecipeReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(blank=True, choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=20)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='main.recipeshare')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='RecipeOrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('serving_note', models.CharField(blank=True, max_length=160)),
                ('custom_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('quoted', 'Quoted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='requested', max_length=20)),
                ('quoted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('admin_note', models.TextField(blank=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending Quote'), ('awaiting', 'Awaiting Payment'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('quote_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_requests', to='main.recipeshare')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_order_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recipe Order Request',
                'verbose_name_plural': 'Recipe Order Requests',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='recipereaction',
            constraint=models.UniqueConstraint(fields=('recipe', 'user'), name='unique_recipe_reaction_per_user'),
        ),
    ]
