# Generated by Django 4.2.26 on 2026-03-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('category', models.CharField(choices=[('starters', 'Starters'), ('main_course', 'Main Course'), ('biryani', 'Biryani'), ('breads', 'Breads'), ('rice', 'Rice & Noodles'), ('snacks', 'Snacks'), ('beverages', 'Beverages'), ('desserts', 'Desserts')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/')),
                ('is_veg', models.BooleanField(default=True)),
            ],
        ),
    ]
